### ISSUE TITLE
Bundled SQLite built with support for dynamically loaded module disabled unusable for survey_pi

### ISSUE THREAD

**Issue by nohal** [OpenCPN/opencpn-libs#13]
https://github.com/OpenCPN/opencpn-libs/blob/main/sqlite/CMakeLists.txt#L29-L33 makes the bundled SQLite library unusable for the survey plugin which uses the `mod_spatialite` module on platforms where it is used.

**Comment by leamas** [comment]
hm... One hand hand we should think twice before changing this which no doubt is used in multiple places.

Could we just conditionalize this, let it depend on a cmake configuration variable  so that the default is as today, but it is possible for the survey plugin to disable it? 

If you make such a patch, please feel free to commit it to devel so we can evaluate it. As long as the defaults are as of the current situation we should not break any eggs.

Thoughts?
